### ISSUE TITLE
TT/SW showing up as available when not

### ISSUE THREAD

**Issue by cmaggard** [wolfman2000/stumpy#88] opened 2018-08-13 04:48 UTC
Relaying this on from a user in one of my Discords that happened upon it.

![image](https://user-images.githubusercontent.com/2081/44013263-8430789e-9e92-11e8-9d24-57faf548a4b3.png)

With this particular combination of items/Aghanim state, TT shows as enterable when it isn't, and SW shows as glitch-enterable, when it isn't.

**Comment by cmaggard** [comment] 2018-08-13 04:53
I believe the fix is that hookshot is also required for this line: https://github.com/wolfman2000/stumpy/blob/master/src/app/map/dungeon-locations/dungeon-location.service.ts#L687

**Comment by cmaggard** [comment] 2018-08-13 04:54
In addition, https://github.com/wolfman2000/stumpy/blob/master/src/app/map/dungeon-locations/dungeon-location.service.ts#L682 is erroneous in that hammer or gloves are still required for the dry route.

**Comment by wolfman2000** [comment] 2018-08-14 21:15
...didn't think I had to worry about insane situations like this. How'd Agahnim get defeated like this?

I'm kind of unsure on how to go about this. Should I disable boss killing for those that don't have the items? What if someone wants just the bosses checked off?

I'm certainly open for discussion on this one.

**Comment by lemabr01** [comment] 2018-08-14 21:19
In this case, I'm assuming aga1 got killed with fighter sword + cape but it isn't marked because it doesn't impact what's available. Not being able to check aga1 off unless you have sword+cape or sword2 would be a good fix I think.

**Comment by cmaggard** [comment] 2018-08-14 21:50
This was the actual game state that led to it:
![image](https://cdn.discordapp.com/attachments/442741685890580482/478417893743263744/Capture.JPG)

**Comment by cmaggard** [comment] 2018-08-14 21:52
As you can see, still no hookshot, but SW/TT still show as accessible.

**Comment by wolfman2000** [comment] 2018-08-19 12:38
The logical issue is resolved by #90. The checking of Agahnim without means to enter the castle tower is not, but that is by design. At some point, I hope to allow for an entrance randomizer mode to be implemented, which would eliminate the need for the cape or master sword. Hopefully that is still reasonable.

**Closed by wolfman2000** 2018-08-19 12:38 UTC
